name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy when code is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Ensure the kubeconfig directory exists
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Debug Kubernetes Contexts
        run: |
          kubectl config get-contexts  # Show available contexts
          kubectl config use-context kind-kind-my-cluster  # Set correct context
          kubectl cluster-info --context kind-kind-my-cluster  # Verify connection

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/my-app my-app=myrepo/myimage:latest --namespace=default --server=https://127.0.0.1:40253
          kubectl rollout status deployment/my-app --namespace=default --server=https://127.0.0.1:40253
