name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy when code is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context kind-my-cluster  # Ensure correct cluster
          kubectl cluster-info

      - name: Debug Kubernetes Connection
        run: kubectl get nodes  # Check if connection works

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/my-app my-app=myrepo/myimage:latest --namespace=default
          kubectl rollout status deployment/my-app --namespace=default
